project 'SwpRequestDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.0'

target 'SwpRequestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwpRequestDemo
  inhibit_all_warnings!

  pod 'SwpRequest'

end
